// Restaurant List Data
const resList = [
    {
      id: "1",
      name: "KFC",
      cuisines: ["Burgers", "Fast Food"],
      avgRating: 4.3,
      costForTwo: 40000,
      sla: { deliveryTime: 24, lastMileTravel: 1.2 },
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/12/9/377e9327-3ca7-48ac-b36c-96f5bf6e186a_671928.JPG",
      locality: "7th Block",
      areaName: "Koramangala",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "ITEMS", subHeader: "AT ₹59" },
    },
    {
      id: "2",
      name: "Paragon Restaurant",
      cuisines: ["Kerala", "Biryani", "South Indian"],
      avgRating: 4.8,
      costForTwo: 60000,
      sla: { deliveryTime: 30, lastMileTravel: 2.5 },
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/2/13/b750551b-1adc-4c9f-bc66-2e49b33518fc_1043798.sss.jpg",
      locality: "Mavoor Road",
      areaName: "Calicut",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "FLAT 20%", subHeader: "UPTO ₹100" },
    },
    {
      id: "3",
      name: "Rahmath Hotel",
      cuisines: ["Biryani", "South Indian", "Seafood"],
      avgRating: 4.6,
      costForTwo: 55000,
      sla: { deliveryTime: 32, lastMileTravel: 1.8 },
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/4/39699e10-c8da-4661-93cd-ebe039b715fb_846957.jpg",
      locality: "Palayam",
      areaName: "Calicut",
      availability: { opened: false },
      aggregatedDiscountInfoV3: { header: "SPECIAL DEAL", subHeader: "EXTRA ₹50 OFF" },
    },
    {
      id: "4",
      name: "Domino's Pizza",
      cuisines: ["Pizza", "Italian"],
      avgRating: 4.4,
      costForTwo: 50000,
      sla: { deliveryTime: 25, lastMileTravel: 3.0 },
      cloudinaryImageId: "dominos-image-id",
      locality: "MG Road",
      areaName: "Bangalore",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "BUY 1 GET 1", subHeader: "FREE" },
    },
    {
      id: "5",
      name: "McDonald's",
      cuisines: ["Burgers", "Fast Food"],
      avgRating: 4.2,
      costForTwo: 35000,
      sla: { deliveryTime: 20, lastMileTravel: 2.3 },
      cloudinaryImageId: "mcdonalds-image-id",
      locality: "Indiranagar",
      areaName: "Bangalore",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "MEAL", subHeader: "AT ₹149" },
    },
    {
      id: "6",
      name: "Empire Restaurant",
      cuisines: ["North Indian", "Mughlai", "Biryani"],
      avgRating: 4.5,
      costForTwo: 60000,
      sla: { deliveryTime: 35, lastMileTravel: 2.8 },
      cloudinaryImageId: "empire-image-id",
      locality: "Brigade Road",
      areaName: "Bangalore",
      availability: { opened: false },
      aggregatedDiscountInfoV3: { header: "FLAT 15%", subHeader: "UPTO ₹75" },
    },
    {
      id: "7",
      name: "Mehfil Biryani",
      cuisines: ["Hyderabadi", "Biryani"],
      avgRating: 4.1,
      costForTwo: 45000,
      sla: { deliveryTime: 40, lastMileTravel: 4.0 },
      cloudinaryImageId: "mehfil-image-id",
      locality: "Hitech City",
      areaName: "Hyderabad",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "EXTRA 10%", subHeader: "ON ALL ORDERS" },
    },
    {
      id: "8",
      name: "Behrouz Biryani",
      cuisines: ["Mughlai", "Biryani"],
      avgRating: 4.7,
      costForTwo: 70000,
      sla: { deliveryTime: 28, lastMileTravel: 2.1 },
      cloudinaryImageId: "behrouz-image-id",
      locality: "Banashankari",
      areaName: "Bangalore",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "FLAT 25%", subHeader: "ON ROYAL MEALS" },
    },
    {
      id: "9",
      name: "Barbeque Nation",
      cuisines: ["BBQ", "Grill", "North Indian"],
      avgRating: 4.6,
      costForTwo: 90000,
      sla: { deliveryTime: 45, lastMileTravel: 5.0 },
      cloudinaryImageId: "bbq-nation-image-id",
      locality: "Marathahalli",
      areaName: "Bangalore",
      availability: { opened: false },
      aggregatedDiscountInfoV3: { header: "PARTY OFFER", subHeader: "GROUP DISCOUNT" },
    },
    {
      id: "10",
      name: "Subway",
      cuisines: ["Healthy", "Sandwiches"],
      avgRating: 4.2,
      costForTwo: 30000,
      sla: { deliveryTime: 22, lastMileTravel: 1.5 },
      cloudinaryImageId: "subway-image-id",
      locality: "Electronic City",
      areaName: "Bangalore",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "BUY 1 GET 1", subHeader: "FREE" },
    },
    {
      id: "11",
      name: "Haldiram's",
      cuisines: ["Indian Sweets", "North Indian"],
      avgRating: 4.3,
      costForTwo: 40000,
      sla: { deliveryTime: 18, lastMileTravel: 1.0 },
      cloudinaryImageId: "haldirams-image-id",
      locality: "Connaught Place",
      areaName: "Delhi",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "FLAT 10%", subHeader: "ON SWEETS" },
    },
    {
      id: "12",
      name: "Bikanervala",
      cuisines: ["Indian Sweets", "Fast Food"],
      avgRating: 4.4,
      costForTwo: 38000,
      sla: { deliveryTime: 20, lastMileTravel: 1.3 },
      cloudinaryImageId: "bikanervala-image-id",
      locality: "Lajpat Nagar",
      areaName: "Delhi",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "EXTRA ₹50", subHeader: "ON ₹499 ORDERS" },
    },
    {
      id: "13",
      name: "Pizza Hut",
      cuisines: ["Pizza", "Italian"],
      avgRating: 4.1,
      costForTwo: 45000,
      sla: { deliveryTime: 27, lastMileTravel: 3.2 },
      cloudinaryImageId: "pizza-hut-image-id",
      locality: "Rajajinagar",
      areaName: "Bangalore",
      availability: { opened: true },
      aggregatedDiscountInfoV3: { header: "MEGA OFFER", subHeader: "₹199 PIZZA" },
    }
  ];


// Exporting the data

export default resList;